"""
After Effects headless bridge.

Responsibilities:
1. Generate ExtendScript/JSX that updates named text layers in a .aep file
   and enables Motion Blur (Shutter Angle 360°) on the composition.
2. Execute that JSX script against After Effects without opening the GUI.
3. Build and run the aerender CLI command to produce the final MP4.
"""

import json
import logging
import os
import platform
import subprocess
import sys
import tempfile
from pathlib import Path

logger = logging.getLogger(__name__)

# ---------------------------------------------------------------------------
# aerender path resolution
# ---------------------------------------------------------------------------

_AERENDER_PATHS: dict[str, list[str]] = {
    "Windows": [
        r"C:\Program Files\Adobe\Adobe After Effects 2025\Support Files\aerender.exe",
        r"C:\Program Files\Adobe\Adobe After Effects 2024\Support Files\aerender.exe",
        r"C:\Program Files\Adobe\Adobe After Effects 2023\Support Files\aerender.exe",
    ],
    "Darwin": [
        "/Applications/Adobe After Effects 2025/aerender",
        "/Applications/Adobe After Effects 2024/aerender",
        "/Applications/Adobe After Effects 2023/aerender",
    ],
    "Linux": [
        "/opt/Adobe/AfterEffects2025/aerender",
        "/opt/Adobe/AfterEffects2024/aerender",
    ],
}

_AFTERFX_PATHS: dict[str, list[str]] = {
    "Windows": [
        r"C:\Program Files\Adobe\Adobe After Effects 2025\Support Files\AfterFX.exe",
        r"C:\Program Files\Adobe\Adobe After Effects 2024\Support Files\AfterFX.exe",
    ],
    "Darwin": [
        "/Applications/Adobe After Effects 2025/Adobe After Effects 2025.app/Contents/MacOS/After Effects",
        "/Applications/Adobe After Effects 2024/Adobe After Effects 2024.app/Contents/MacOS/After Effects",
    ],
    "Linux": [],
}


def get_aerender_path() -> str:
    """
    Returns the aerender binary path.
    Checks AERENDER_PATH env var first, then platform-specific defaults.
    Raises FileNotFoundError if none found.
    """
    env_override = os.environ.get("AERENDER_PATH")
    if env_override and Path(env_override).exists():
        return env_override

    system = platform.system()
    candidates = _AERENDER_PATHS.get(system, [])
    for path in candidates:
        if Path(path).exists():
            return path

    raise FileNotFoundError(
        f"aerender not found on {system}. Install Adobe After Effects or set the "
        "AERENDER_PATH environment variable to the aerender binary location."
    )


def get_afterfx_path() -> str | None:
    """
    Returns the After Effects executable path for running JSX scripts (-r flag).
    Returns None if not found (caller falls back to aerender-based JSX execution).
    """
    env_override = os.environ.get("AFTERFX_PATH")
    if env_override and Path(env_override).exists():
        return env_override

    system = platform.system()
    for path in _AFTERFX_PATHS.get(system, []):
        if Path(path).exists():
            return path
    return None


# ---------------------------------------------------------------------------
# JSX script generation
# ---------------------------------------------------------------------------

_JSX_TEMPLATE = """\
// Auto-generated by ae_bridge.py — do not edit manually.
var projectPath = new File({project_path_json});
app.open(projectPath);

var proj = app.project;

// Find target composition by index (1-based) or name
var comp = null;
for (var i = 1; i <= proj.numItems; i++) {{
    if (proj.item(i) instanceof CompItem && proj.item(i).name === {comp_name_json}) {{
        comp = proj.item(i);
        break;
    }}
}}

if (comp === null) {{
    // Fallback: use first composition
    for (var i = 1; i <= proj.numItems; i++) {{
        if (proj.item(i) instanceof CompItem) {{
            comp = proj.item(i);
            break;
        }}
    }}
}}

if (comp === null) {{
    alert("ae_bridge: No composition found in project. Aborting.");
    app.quit();
}}

// ---- Motion Blur: Shutter Angle 360° ----
comp.motionBlur = true;
comp.shutterAngle = 360;
comp.shutterPhase = -180;

// Enable motion blur on every layer
for (var li = 1; li <= comp.numLayers; li++) {{
    try {{ comp.layer(li).motionBlur = true; }} catch (e) {{}}
}}

// ---- Text Layer Updates ----
var updates = {updates_json};

for (var ui = 0; ui < updates.length; ui++) {{
    var u = updates[ui];
    for (var li = 1; li <= comp.numLayers; li++) {{
        var layer = comp.layer(li);
        if (layer.name === u.layer) {{
            try {{
                var textProp = layer.property("Text").property("Source Text");
                var textDoc = textProp.value;
                textDoc.text = u.text;
                textProp.setValue(textDoc);
            }} catch (e) {{
                // Layer exists but may not be a text layer
            }}
        }}
    }}
}}

proj.save();
app.quit();
"""


def generate_jsx(
    project_path: str,
    comp_name: str,
    text_updates: list[dict],
    output_jsx_path: str | None = None,
) -> str:
    """
    Generates an ExtendScript JSX string that:
    - Opens the .aep project
    - Enables Motion Blur with Shutter Angle 360° on the composition
    - Updates named text layers with provided values
    - Saves and closes the project

    Args:
        project_path: Absolute path to the .aep file.
        comp_name: Name of the target composition inside the project.
        text_updates: List of {"layer": "<name>", "text": "<value>"} dicts.
        output_jsx_path: If provided, writes the script to this path.

    Returns:
        The JSX script as a string.
    """
    jsx = _JSX_TEMPLATE.format(
        project_path_json=json.dumps(project_path),
        comp_name_json=json.dumps(comp_name),
        updates_json=json.dumps(text_updates, ensure_ascii=False),
    )

    if output_jsx_path:
        Path(output_jsx_path).write_text(jsx, encoding="utf-8")
        logger.debug("JSX script written to %s", output_jsx_path)

    return jsx


def execute_jsx(jsx_content: str, ae_executable: str | None = None) -> subprocess.CompletedProcess:
    """
    Executes a JSX script against After Effects headlessly.

    Strategy:
    1. Write JSX to a temp file.
    2. Try AfterFX.exe/After Effects -r <jsx_path> (cleanest headless mode).
    3. If AfterFX not found, raises RuntimeError with instructions.

    Args:
        jsx_content: The ExtendScript source code.
        ae_executable: Override path to the After Effects executable.

    Returns:
        CompletedProcess from subprocess.run().
    """
    with tempfile.NamedTemporaryFile(
        mode="w", suffix=".jsx", prefix="ae_bridge_", delete=False, encoding="utf-8"
    ) as f:
        f.write(jsx_content)
        jsx_path = f.name

    try:
        binary = ae_executable or get_afterfx_path()
        if not binary:
            raise RuntimeError(
                "Adobe After Effects executable not found. Set AFTERFX_PATH env var or "
                "ensure After Effects is installed. The JSX was written to: " + jsx_path
            )

        cmd = [binary, "-r", jsx_path]
        logger.info("Executing JSX: %s -r %s", binary, jsx_path)
        result = subprocess.run(cmd, capture_output=True, text=True, timeout=120)
        if result.returncode != 0:
            logger.error("JSX execution failed (exit %d):\n%s", result.returncode, result.stderr)
        else:
            logger.info("JSX execution completed successfully.")
        return result
    finally:
        try:
            os.unlink(jsx_path)
        except OSError:
            pass


# ---------------------------------------------------------------------------
# aerender command + execution
# ---------------------------------------------------------------------------


def build_aerender_command(
    aerender_bin: str,
    project_path: str,
    comp_name: str,
    output_path: str,
    start_frame: int = 0,
    end_frame: int = 179,
    fps: int = 60,
    rs_template: str = "Best Settings",
    om_template: str = "h.264 - Match Source",
) -> list[str]:
    """
    Builds the aerender argument list.

    Motion Blur is controlled via the .aep file (set by execute_jsx before
    this call); aerender honours whatever shutterAngle is saved in the project.
    The -RStemplate "Best Settings" flag instructs aerender to use the
    composition's own render settings (which include the saved shutterAngle).

    Args:
        aerender_bin: Path to the aerender binary.
        project_path: Path to the .aep file (pre-updated by execute_jsx).
        comp_name: Name of the composition to render.
        output_path: Destination MP4 path.
        start_frame: First frame to render (default 0).
        end_frame: Last frame to render (default 179 = 3s @ 60fps).
        fps: Frames per second.
        rs_template: Render Settings template name in AE.
        om_template: Output Module template name in AE.

    Returns:
        List of strings suitable for subprocess.Popen/run.
    """
    return [
        aerender_bin,
        "-project", project_path,
        "-comp", comp_name,
        "-output", output_path,
        "-s", str(start_frame),
        "-e", str(end_frame),
        "-fps", str(fps),
        "-RStemplate", rs_template,
        "-OMtemplate", om_template,
        "-continueOnMissingFootage",
    ]


def run_render(
    aerender_bin: str,
    command: list[str],
    timeout_seconds: int = 600,
) -> int:
    """
    Executes the aerender command and streams its output to the logger.

    Args:
        aerender_bin: Path to aerender (used only for logging).
        command: The full argv list returned by build_aerender_command().
        timeout_seconds: Kill the process if it exceeds this duration.

    Returns:
        Process exit code (0 = success).

    Raises:
        subprocess.TimeoutExpired: If render exceeds timeout_seconds.
    """
    logger.info("Starting aerender: %s", " ".join(command))

    proc = subprocess.Popen(
        command,
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
        text=True,
    )

    try:
        for line in proc.stdout:
            logger.info("[aerender] %s", line.rstrip())
        for line in proc.stderr:
            logger.error("[aerender:err] %s", line.rstrip())
        proc.wait(timeout=timeout_seconds)
    except subprocess.TimeoutExpired:
        proc.kill()
        raise

    if proc.returncode == 0:
        logger.info("aerender finished successfully (exit 0).")
    else:
        logger.error("aerender failed with exit code %d.", proc.returncode)

    return proc.returncode
